{application,neural_network,
             [{description,"A neural network made up of layers of neurons connected to each other to form a relationship allowing it to learn.\n"},
              {modules,['Elixir.Mix.Tasks.And','Elixir.Mix.Tasks.Learn',
                        'Elixir.Mix.Tasks.Or','Elixir.NeuralNetwork',
                        'Elixir.NeuralNetwork.Connection',
                        'Elixir.NeuralNetwork.DataFactory',
                        'Elixir.NeuralNetwork.Layer',
                        'Elixir.NeuralNetwork.Network',
                        'Elixir.NeuralNetwork.Neuron',
                        'Elixir.NeuralNetwork.Trainer']},
              {registered,[]},
              {vsn,"0.1.4"},
              {applications,[kernel,stdlib,elixir,logger]},
              {mod,{'Elixir.NeuralNetwork',[]}}]}.
